version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.6-jessie-browsers
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            virtualenv -p python3 ~/.virtualenvs/tap-hubspot
            source ~/.virtualenvs/tap-hubspot/bin/activate
            pip install .
            pip install pylint
            pylint tap_hubspot -d C,R,W
      - run:
          name: 'Unit Tests'
          command: |
            source ~/.virtualenvs/tap-hubspot/bin/activate
            pip install nose
            nosetests
